# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Actions on Cron

# currently run on Saturday at midnight Hawaii time (UTC - 10)
on:
  schedule:
    - cron: "0 10 * * 6"

# For testing - enable on push
# on:
#   push:
#     branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY}}
      SEND_EMAIL: ${{secrets.SEND_EMAIL}} # not actually a secret. A 0 or 1 flag
      WRITE_TO_FILES: ${{ secrets.WRITE_TO_FILES }} # not acutally a secret. A 0 or 1 flag.
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run start
      - name: Commit and Push files if flag set
        if: ${{ env.WRITE_TO_FILES == '1'}}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git commit -am "github actions commit from node-js-push.yml"
          git push
        shell: bash
